"""Additive dashboard model and owned-file exporter. No HA storage writes."""

import hashlib
import json
import math
import re
from datetime import datetime, timezone
from pathlib import Path

GROUPS = {
    "printer": ("printers", "Принтеры", "mdi:printer"),
    "computer": ("computers", "Рабочие места", "mdi:desktop-classic"),
    "camera": ("cameras", "Видеонаблюдение", "mdi:cctv"),
    "access_point": ("access_points", "Точки доступа", "mdi:access-point"),
    "server": ("servers", "Серверы", "mdi:server"),
    "voip": ("voip", "Телефония · SIP / VoIP", "mdi:phone"),
    "unknown": ("unknown", "Другие устройства", "mdi:devices"),
}
ROOT = "maria-monitor"
OWNER = "# Generated by Maria Network Monitor; schema=1\n"


def site_key(name):
    readable = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:32]
    digest = hashlib.sha256(name.encode("utf-8")).hexdigest()[:12]
    return f"{readable or 'site'}-{digest}"


def utc_now():
    return datetime.now(timezone.utc).isoformat()


def supply_kind(marker):
    text = f"{marker.get('type') or ''} {marker.get('name') or ''}".lower()
    if "waste" in text or "отработ" in text:
        return "waste-toner"
    if any(word in text for word in ("drum", "opc", "барабан", "фотобарабан")):
        return "drum"
    if "toner" in text or "тонер" in text:
        return "toner"
    return "supply"


def printer_health(device):
    data = device.get("printer") or {}
    ipp = data.get("ipp") or {}
    supplies = []
    alerts = []
    markers = list(data.get("markers") or [])
    # Preserve legacy marker identities. Add SNMP-only drum/waste to the UI model
    # without renumbering existing MQTT marker entities or duplicating toner.
    primary_kinds = {supply_kind(marker) for marker in markers}
    for marker in (data.get("snmp") or {}).get("supplies") or []:
        if supply_kind(marker) in ("drum", "waste-toner") and supply_kind(marker) not in primary_kinds:
            markers.append(marker)
    for marker in markers:
        kind = supply_kind(marker)
        percent = marker.get("percent")
        if (not isinstance(percent, (int, float)) or isinstance(percent, bool)
                or not math.isfinite(percent) or not 0 <= percent <= 100):
            percent = None
        warning = kind == "toner" and percent is not None and percent <= 20
        supplies.append({
            "index": marker.get("index"), "name": marker.get("name") or kind,
            "kind": kind, "percent": percent, "warning": warning,
        })
        if warning:
            alerts.append("low-toner")
    raw_reasons = ipp.get("reasons") or []
    reasons = [raw_reasons] if isinstance(raw_reasons, str) else [str(reason) for reason in raw_reasons]
    # Empty/none/idle/processing are not faults. IPP reports explicit severity.
    fault_reasons = [reason for reason in reasons if reason not in ("none", "other")
                    and (reason.endswith(("-warning", "-error")) or any(
                        word in reason for word in ("jam", "empty", "full", "missing", "door-open")))]
    if str(ipp.get("state", "")).lower() in ("stopped", "5"):
        alerts.append("stopped")
    if ipp.get("accepting_jobs") is False:
        alerts.append("not-accepting-jobs")
    if fault_reasons:
        alerts.append("printer-reason")
    if device.get("online") is False:
        alerts.append("offline")
    return {
        "supplies": supplies, "alerts": sorted(set(alerts)),
        "problem": bool(alerts), "status": ipp.get("state"),
        "reasons": reasons, "page_count": data.get("page_count"),
        "queue": ipp.get("queued_jobs"), "accepting_jobs": ipp.get("accepting_jobs"),
        "ipp_observed_at": data.get("ipp_observed_at"),
        "snmp_observed_at": data.get("snmp_observed_at"),
        "ipp_fresh": data.get("ipp_fresh", False),
        "snmp_fresh": data.get("snmp_fresh", False),
    }


def update_inventory(previous, results, observed_at=None):
    """Only successful router polls can remove devices; failures retain last data."""
    observed_at = observed_at or utc_now()
    snapshot = {"schema": 1, "sites": {}}
    for result in results:
        site = result["site"]
        key = site_key(site["name"])
        old = previous.get("sites", {}).get(key, {})
        if result["ok"]:
            old_devices = {item["id"]: item for item in old.get("devices", [])}
            devices = []
            for device in result.get("devices", []):
                prior = old_devices.get(device["id"], {})
                kind = device.get("type", "unknown")
                if kind == "unknown" and prior.get("type"):
                    kind = prior["type"]
                    device["type"] = kind
                item = {
                    "id": device["id"], "name": device["name"], "type": kind,
                    "online": bool(device.get("online")), "observed_at": observed_at,
                    "online_unique_id": device["id"] + "_online",
                }
                if kind == "printer":
                    item["printer"] = printer_health(device)
                devices.append(item)
            for old_device in old.get("devices", []):
                if old_device["id"] in result.get("pending_ids", set()):
                    devices.append({**old_device, "stale": True, "pending_removal": True})
            # Stable identity ordering prevents churn; the frontend sorts by severity.
            devices = sorted({item["id"]: item for item in devices}.values(), key=lambda x: x["id"])
        else:
            devices = old.get("devices", [])
        online = sum(item["online"] for item in devices)
        problems = sum(bool(item.get("printer", {}).get("problem")) for item in devices)
        current = result["ok"] and not result.get("pending_ids")
        snapshot["sites"][key] = {
            "schema": 1, "maria_role": "site_inventory", "site_id": key,
            "name": site["name"], "router_online": bool(result["ok"]),
            "stale": not current, "missing_polls": result.get("missing_polls", {}),
            "inventory_pending": bool(result.get("pending_ids")),
            "diagnostics": result.get("diagnostics", old.get("diagnostics", {})), "observed_at": observed_at,
            "last_success_at": observed_at if result["ok"] else old.get("last_success_at"),
            "total": len(devices), "online": online if current else None,
            "offline": len(devices) - online if current else None,
            "printer_problems": problems if current else None,
            "devices": devices,
        }
    return snapshot


def discovery_configs(site, expire_after):
    key = site["site_id"]
    topic = f"{ROOT}/dashboard/{key}/state"
    common = {
        "state_topic": topic, "availability_topic": f"{ROOT}/availability",
        "payload_available": "online", "payload_not_available": "offline",
        "expire_after": max(expire_after, 900),
        "device": {"identifiers": [f"maria_dashboard_{key}"],
                   "name": f"Maria · {site['name']}", "manufacturer": "Maria Network",
                   "model": "Site statistics"},
    }
    fields = {"inventory": "Inventory", "online": "Online devices",
              "offline": "Offline devices", "printer_problems": "Problem printers"}
    for field, name in fields.items():
        uid = f"maria_dashboard_{key}_{field}"
        data = {**common, "unique_id": uid, "name": name,
                "value_template": "{{ value_json." + ("total" if field == "inventory" else field) + " }}"}
        if field == "inventory":
            # Snapshot must remain visible during monitor/broker outages and HA restart.
            for option in ("availability_topic", "payload_available", "payload_not_available", "expire_after"):
                data.pop(option, None)
            data["json_attributes_topic"] = topic
            data["entity_category"] = "diagnostic"
        else:
            data["state_class"] = "measurement"
            data["value_template"] = "{{ value_json." + field + " | default(0, true) }}"
            data.pop("availability_topic")
            data["availability_mode"] = "all"
            data["availability"] = [
                {"topic": f"{ROOT}/availability", "payload_available": "online", "payload_not_available": "offline"},
                {"topic": topic, "value_template": "{{ 'offline' if value_json.stale else 'online' }}",
                 "payload_available": "online", "payload_not_available": "offline"},
            ]
        yield f"homeassistant/sensor/{uid}/config", data


def dashboard_config(sites):
    views = [{"title": "Все филиалы", "path": "overview", "type": "sections", "max_columns": 3,
              "sections": [{"type": "grid", "column_span": 3, "cards": [{"type": "custom:maria-network-card",
                            "mode": "overview"}]}]}]
    views.append({"title": "Отчёт за день", "path": "daily", "type": "sections", "max_columns": 3,
                  "sections": [{"type": "grid", "column_span": 3, "cards": [
                      {"type": "custom:maria-network-card", "mode": "report"}]}]})
    for site in sites:
        key = site_key(site["name"])
        sections = [{"type": "grid", "column_span": 2, "cards": [
            {"type": "custom:maria-network-card", "mode": "summary", "site_id": key}]}]
        sections.append({"type": "grid", "column_span": 2, "cards": [
            {"type": "custom:maria-network-card", "mode": "report", "site_id": key},
            {"type": "custom:maria-network-card", "mode": "history", "site_id": key}]})
        for _, (group, label, icon) in GROUPS.items():
            sections.append({"type": "grid", "column_span": 2 if group == "printers" else 1, "cards": [
                {"type": "custom:maria-network-card", "mode": "group", "site_id": key,
                 "group": group, "title": label, "icon": icon}]})
        views.append({"title": site["name"], "path": key, "type": "sections", "max_columns": 2,
                      "sections": sections})
    return {"title": "Maria Network Monitor", "views": views}


def write_owned(path, content, owner=OWNER):
    """Idempotent atomic writes; reject foreign files and symlink destinations."""
    path = Path(path)
    if path.is_symlink() or any(parent.is_symlink() for parent in path.parents):
        raise ValueError("Dashboard destination must not be a symlink")
    if path.exists():
        old = path.read_text(encoding="utf-8")
        if not old.startswith(owner):
            raise ValueError(f"Refusing to overwrite unowned file: {path.name}")
        if old == content:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    if temporary.is_symlink():
        raise ValueError("Dashboard temporary file must not be a symlink")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)
    return True


def export_dashboard(sites, directory):
    # JSON flow-style documents are valid YAML 1.2; no new Python dependency.
    content = OWNER + json.dumps(dashboard_config(sites), ensure_ascii=False, indent=2) + "\n"
    return write_owned(Path(directory) / "maria-network-monitor.yaml", content)


def export_assets(directory):
    source = Path(__file__).parent / "frontend" / "maria-network-card.js"
    content = source.read_text(encoding="utf-8")
    return write_owned(Path(directory) / "maria-network-card.js", content,
                       "// Generated by Maria Network Monitor; schema=1\n")


class NewPrinterDiscovery:
    """Forward new printer entities only; transient missing metrics never tombstone."""
    def __init__(self, client, published):
        self.client = client
        self.published = published

    def publish(self, topic, payload, **kwargs):
        if not payload or topic in self.published:
            return None
        result = self.client.publish(topic, payload, **kwargs)
        self.published.add(topic)
        return result
